### PR TITLE
Request the READ_MEDIA_AUDIO permission

### LINKED ISSUE #83: Sweyer no longer has access to music
### Steps to reproduce

1. Open the newest 1.0.8 version on a phone with Android 13
2. The app is not asking to grant storage permissions and the app shows that there is no music on my phone.
3. Deleted the app data and cache and opened it again.
4. This time the app askes to grant storage permissions.
5. The user is redirected to the settings page to grant the permission manually, but there is no option to grant any permission. The settings app shows that the app does not require any permission.

### What did you expect?

To see music and to be able to grant the app access to it.

### What happened instead?

The app does not have access to the music.

### Sweyer version

1.0.8

### Android version

Android 13

### PR DESCRIPTION
**Pull request by Abestanis**
On Android 13, `READ_EXTERNAL_STORAGE` has been split into more [granular permissions](https://developer.android.com/about/versions/13/behavior-changes-13#granular-media-permissions), like `READ_MEDIA_AUDIO`. We need to request this permission to be able to query music from the content provider service. Fixes #83.

The `READ_MEDIA_AUDIO` will automatically be granted when requested if `READ_EXTERNAL_STORAGE` was previously granted.

### CODE REVIEW

**Comment by Abestanis** [comment]
Making the tests pass again was harder than the actual fix. 😄

This fix was tested on an Android 13 phone and an emulator with Android 10.
I think we should make a `1.8.1` release as soon as possible, to make the app usable on Android 13+ phones again.

File: test/routes/home_route_test.dart [hunk 1]
```diff
@@ -13,53 +13,75 @@ void main() {
...
-  testWidgets('permissions screen - shows toast and opens settings when permissions are denied',
-      (WidgetTester tester) async {
-    late PermissionsChannelObserver permissionsObserver;
-    await setUpAppTest(() {
-      permissionsObserver = PermissionsChannelObserver(tester.binding);
-      permissionsObserver.setPermission(Permission.storage, PermissionStatus.denied);
+    // On Android 13+ the storage permission is removed and reports as permanentlyDenied.
+    // If the user granted audio permissions, we have access to the music
+    // and don't want to show the permission request screen.
+    testWidgets('does not show when one removed permission is permanently denied', (WidgetTester tester) async {
```
Comment (nt4f04uNd) [inline test/routes/home_route_test.dart:46]: why not test it for both?
on API `<33` he `Permission.audio` is permantently denied

File: test/fakes/fake_just_audio.dart [hunk 2]
```diff
@@ -137,8 +142,10 @@ class MockAudioPlayer implements AudioPlayerPlatform {
     }
     _audioSource = audioSource;
     _index = request.initialIndex ?? 0;
-    // Simulate loading time.
-    await Future<dynamic>.delayed(const Duration(milliseconds: 100));
+    if (binding.inTest) {
+      // Simulate loading time.
+      await Future<void>.delayed(const Duration(milliseconds: 100));
```
Comment (nt4f04uNd) [inline test/fakes/fake_just_audio.dart:147]: Can you explain this change?

File: lib/logic/permissions.dart [hunk 3]
```diff
@@ -7,22 +7,28 @@ class Permissions {
...
 
   Future<void> init() async {
     _permissionStorageStatus = await Permission.storage.status;
+    _permissionAudioStatus = await Permission.audio.status;
   }
 
   Future<void> requestClick() async {
-    _permissionStorageStatus = await Permission.storage.request();
-    if (_permissionStorageStatus == PermissionStatus.granted) {
+    final responses = await [Permission.storage, Permission.audio].request();
```
Comment (nt4f04uNd) [inline lib/logic/permissions.dart:25]: lol, cool 👍

File: lib/logic/permissions.dart [hunk 4]
```diff
@@ -7,22 +7,28 @@ class Permissions {
...
-  bool get granted => _permissionStorageStatus == PermissionStatus.granted;
+  bool get granted => _permissionStorageStatus == PermissionStatus.granted
+      || _permissionAudioStatus == PermissionStatus.granted;
 
   /// Returns true if permissions were not granted
   bool get notGranted => !granted;
 
   Future<void> init() async {
     _permissionStorageStatus = await Permission.storage.status;
+    _permissionAudioStatus = await Permission.audio.status;
```
Comment (nt4f04uNd) [inline lib/logic/permissions.dart:21]: maybe we should use DeviceInfo API level call storage status only `<33`, and audio status only `>=33`?

File: test/test.dart [hunk 5]
```diff
@@ -189,7 +189,11 @@ Future<void> setUpAppTest([VoidCallback? configureFakes]) async {
   ThemeControl.instance.init();
   ThemeControl.instance.initSystemUi();
   await Permissions.instance.init();
-  await ContentControl.instance.init();
+  if (binding.inTest) {
+    await binding.runAsync(() => ContentControl.instance.init());
```
[the remark this answers is not in the document]
Comment (Abestanis) [reply test/test.dart:193]: Because we are doing real async work with the `await Future<void>.delayed(const Duration(milliseconds: 100));` in `test/fakes/fake_just_audio.dart:147`

This caused the test to hang (see [here](https://github.com/nt4f04uNd/sweyer/actions/runs/4644452852/jobs/8219736699#step:3:875)).

Originally, I wanted to is `binding.delayed` instead of `Future.delayed`, but because this is apparently executed in the background while the test is running, it threw an error about a reentrant use of the delayed function.

File: test/fakes/fake_just_audio.dart (hunk 2 above)
Comment (Abestanis) [reply test/fakes/fake_just_audio.dart:147]: See, my other response. I added the `binding.inTest` check because it occurred to me that outside of the test we don't need to delay.

File: test/routes/home_route_test.dart [hunk 6]
```diff
@@ -13,53 +13,75 @@ void main() {
...
+    testWidgets('shows toast and opens settings when permissions are denied', (WidgetTester tester) async {
+      late PermissionsChannelObserver permissionsObserver;
+      await setUpAppTest(() {
+        permissionsObserver = PermissionsChannelObserver(tester.binding);
+        permissionsObserver.setPermission(Permission.storage, PermissionStatus.denied);
+        permissionsObserver.setPermission(Permission.audio, PermissionStatus.denied);
+      });
+      await tester.runAppTest(() async {
+        permissionsObserver.setPermission(Permission.storage, PermissionStatus.permanentlyDenied);
+        permissionsObserver.setPermission(Permission.audio, PermissionStatus.permanentlyDenied);
```
[the remark this answers is not in the document]
Comment (Abestanis) [reply test/routes/home_route_test.dart:68]: It was like this before, but we are testing the behaviour when the user denies the system dialog.

File: lib/logic/permissions.dart (hunk 4 above)
Comment (Abestanis) [reply lib/logic/permissions.dart:21]: We want to request both of them at the same time to automatically get the `audio` permission if `storage` was previously granted.

File: test/test.dart (hunk 5 above)
[the remark this answers is not in the document]
Comment (nt4f04uNd) [reply test/test.dart:193]: It appears to me it timed out there, because you didn't update this specific permission test. But I think I'm okay with this change overall.

File: test/routes/home_route_test.dart (hunk 6 above)
[the remark this answers is not in the document]
Comment (nt4f04uNd) [reply test/routes/home_route_test.dart:68]: Seems like it could just be one call in set up step, but skipping this in this PR

File: lib/logic/permissions.dart (hunk 4 above)
Comment (nt4f04uNd) [reply lib/logic/permissions.dart:21]: Didn't really get what you mean, but so be it.

**Comment by nt4f04uNd** [comment]
I'll be able to re publish the app in a few hours. Waiting for additional test on API `<33` and will merge this.

**Comment by nt4f04uNd** [comment]
Also, please iterate the version in pubspec and update the CHANGELOG

File: lib/logic/permissions.dart (hunk 4 above)
Comment (Abestanis) [reply lib/logic/permissions.dart:21]: Ah, sorry, I was in a hurry and didn't really read what you were writing. You are right, it is better to only check for the required permission, I changed it. What I meant is that we can (and I think we should) request both permissions simultaneously.
